name: Build 
on: 
  workflow_call:

jobs:
  build_cpp:
    name: Build C++
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Build the file
        run: g++ hello.cpp -o hello
      - uses: actions/upload-artifact@v4
        with:
          name: ubuntu-executable
          path: hello
          retention-days: 1
