name: Test 
on: 
 push: 

jobs:
  build_cpp:
    uses: ./.github/workflows/build.yaml
  test_cpp:
    name: Test executable
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ubuntu-executable
      - name: Test the executable
        run: |
          chmod 755 hello
          ./hello
